### PR TITLE
TRANSLATION: Russian

### LINKED ISSUE #2863: Added Russian translation
I've translated the README.ru.md and added necessary links in both the main README and the README in `./translations`.
#2856

### PR DESCRIPTION
**Pull request by Lesterrry**
I've translated the README to Russian and added all links in the main README and README inside of `./translations`.\
This PR will close #2863

### CODE REVIEW

**Review by github-education — CHANGES_REQUESTED** [review]
**Hi Lesterrry,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/Lesterrry/Lesterrry.md` exists*
*Please ensure all changes are contained within the `_data/Lesterrry/` directory. Invalid file paths:* 

	* `README.md`
	* `translations/README.md`
	* `translations/README.ru.md`


Feel free to re-request a review from me and I'll come back and take a look!

**Comment by Lesterrry** [comment]
This request closes #2863

**Comment by StarOnTheSky** [comment]
Will our translations be merged?

**Comment by Lesterrry** [comment]
> Will our translations be merged?

Let's hope they will be

**Comment by elisemoe** [comment]
Thank you so much @Lesterrry!! This is incredibly helpful for other students to participate ✨ 💖

**Pull request merged**
