### PR TITLE
Added Thai translation for README.md

### LINKED ISSUE #3504: Add Thai Translation

### PR DESCRIPTION
**Pull request by pknn**
Added Thai Translation Github Graduation Readme 🎓

close #3504

### CODE REVIEW

**Review by github-education — DISMISSED** [review]
**Hi pknn,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *I'm not seeing a valid student developer pack approval, please submit an [application](https://education.github.com/discount_requests/student_application?utm_source=2021-06-05-GitHubGraduation) to get started*
* *Uh Oh! I've found some issues with where you have created your files!* 
	*Please ensure all changes are contained within the `_data/pknn/` directory. Invalid file paths:* 

	* `translations/README.md`
	* `translations/README.th.md`


Feel free to re-request a review from me and I'll come back and take a look!

**Comment by pknn** [comment]
close #3504

**Comment by juanpflores** [comment]
Hi @pknn 👋🏼 
Thanks for helping with this translation ⭐ Do you mind adding the translation to the main README as well so that people can access it quicker 💨.

**Comment by pknn** [comment]
@juanpflores Hey! I've added the translation to the main README 🌟. Glad to be able to contribute to this event 💯

**Review by juanpflores — APPROVED** [review]

**Comment by juanpflores** [comment]
⭐ Thanks for making this contribution @pknn. It is amazing ✨

**Pull request merged**
