### PR TITLE
Translation: Add Chinese Translation README

### PR DESCRIPTION
**Pull request by Xunzhuo**
Signed-off-by: Xunzhuo <mixdeers@gmail.com>

# Translation the Class of 2022🎓

Translation: Add Chinese Translation README

resolve: https://github.com/education/GitHubGraduation-2022/issues/2820

cc @github-education

### CODE REVIEW

**Review by github-education — CHANGES_REQUESTED** [review]
**Hi Xunzhuo,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/Xunzhuo/Xunzhuo.md` exists*
*Please ensure all changes are contained within the `_data/Xunzhuo/` directory. Invalid file paths:* 

	* `README.md`
	* `translations/README.md`
	* `translations/README.zh.md`


Feel free to re-request a review from me and I'll come back and take a look!

**Comment by Xunzhuo** [comment]
Hi @elisemoe , this PR contains Chinese Localization Translation REAMD, PTAL, THANKS!

**Comment by elisemoe** [comment]
Wow! Thank-you @Xunzhuo!! This is going to be so helpful for others to join the event 💖 💖 💖

**Comment by juanpflores** [comment]
Thanks for making this! ⭐ ❤️

**Pull request merged**
