### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EitanG100**
[EitanG100.md](https://github.com/education/GitHubGraduation-2022/files/8609698/EitanG100.md)
# Application to the Class of 2022🎓

This pull request template helps you complete an application to the **Class of 2022**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`) and markdown file.
- [x] I have submitted a [swag shipping form](https://airtable.com/shrVMo8ItH4wjsO9f).
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20210605T160000Z%2F20210605T173000Z&text=GitHub%20Graduation%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.
[EitanG100.md](https://github.com/education/GitHubGraduation-2022/files/8609710/EitanG100.md)

### CODE REVIEW

**Review by github-education — CHANGES_REQUESTED** [review]
**Hi EitanG100,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/EitanG100/EitanG100.md` exists*
*Please ensure all changes are contained within the `_data/EitanG100/` directory. Invalid file paths:* 

	* `README.md`


Feel free to re-request a review from me and I'll come back and take a look!

**Review by SuperAayush — CHANGES_REQUESTED** [review]
The filename should be the same as your Github username and you don't need to copy the whole readme instead only copy this :
`
---
name: FULLNAME-OR-NICKNAME # No longer than 28 characters
institution: INSTITUTION-NAME 🚩 # no longer than 58 characters
quote: YOUR-SENIOR-QUOTE # no longer than 100 characters, avoid using quotes(") to guarantee the format remains the same.
github_user: YOUR-GITHUB-USERNAME
---

`

Don't forget to add your credentials in the above code

**Comment by EitanG100** [comment]
I do not understand what the issue is. Can someone please help???

**Comment by EitanG100** [comment]
[Uploading GitHubGraduation-2022.zip…]()

**Review by EitanG100 — COMMENTED** [review]
---
name: Ethan "Eitan" Gotian
institution: University of Pennsylvania
quote: Dream big, work hard, stay focused, and surround yourself with good people
github_user: EitanG100
---

**Review by github-education — CHANGES_REQUESTED** [review]
**Hi EitanG100,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/EitanG100/EitanG100.md` exists*
*Please ensure all changes are contained within the `_data/EitanG100/` directory. Invalid file paths:* 

	* `README.md`


Feel free to re-request a review from me and I'll come back and take a look!

**Review by github-education — CHANGES_REQUESTED** [review]
**Hi EitanG100,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/EitanG100/EitanG100.md` exists*
*Please ensure all changes are contained within the `_data/EitanG100/` directory. Invalid file paths:* 

	* `README.md`


Feel free to re-request a review from me and I'll come back and take a look!

**Pull request merged**
