### PR TITLE
Thai translation improvement

### PR DESCRIPTION
**Pull request by phwt**
Update Thai translation:
- Clearer and more consistent wording
- Fix typo

### CODE REVIEW

**Review by github-education — CHANGES_REQUESTED** [review]
**Hi phwt,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/phwt/phwt.md` exists*
*Please ensure all changes are contained within the `_data/phwt/` directory. Invalid file paths:* 

	* `translations/README.th.md`


Feel free to re-request a review from me and I'll come back and take a look!

**Review by github-education — CHANGES_REQUESTED** [review]
**Hi phwt,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/phwt/phwt.md` exists*
*Please ensure all changes are contained within the `_data/phwt/` directory. Invalid file paths:* 

	* `translations/README.th.md`


Feel free to re-request a review from me and I'll come back and take a look!

**Comment by phwt** [comment]
@elisemoe - sorry for the ping.

**Review by juanpflores — APPROVED** [review]

**Comment by juanpflores** [comment]
Thanks for all your help!

**Pull request merged**
