### PR TITLE
Create README.it.md

### PR DESCRIPTION
**Pull request by elB4RTO**
I have made a translation for the italian language.
I know I'm late, so sorry, but I've seen it just today.
**(not an application for the Graduation)**

### CODE REVIEW

**Review by github-education — CHANGES_REQUESTED** [review]
**Hi elB4RTO,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *I'm not seeing a valid student developer pack approval, please submit an [application](https://education.github.com/discount_requests/student_application?utm_source=2021-06-05-GitHubGraduation) to get started*
* *It looks like you still need to fill out the [shipping form](https://airtable.com/shrVMo8ItH4wjsO9f) to continue*
* *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/elB4RTO/elB4RTO.md` exists*
*Please ensure all changes are contained within the `_data/elB4RTO/` directory. Invalid file paths:* 

	* `translations/README.it.md`

* *You need to agree to our COC on the shipping form pretty please!*

Feel free to re-request a review from me and I'll come back and take a look!

**Comment by elB4RTO** [comment]
Hi 🤖,
this is not an application :)
I've added a new translation file

**Comment by juanpflores** [comment]
thanks you for submitting this translation ⭐

**Comment by juanpflores** [comment]
✅ Merged

**Pull request merged**
