### PR TITLE
Create Arabic Translation (Review needed)

### PR DESCRIPTION
**Pull request by OmarDev100**
# Arabic Translation🎓

This pull request helps more people to join the Year Book of 2022 ;). As Arabic is really popular language :+1: 

## Checklist ✅

- [X] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [X] I understand I should not tag or add a reviewer to this Pull Request.

### CODE REVIEW

**Review by github-education — CHANGES_REQUESTED** [review]
**Hi OmarDev100,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/OmarDev100/OmarDev100.md` exists*
*Please ensure all changes are contained within the `_data/OmarDev100/` directory. Invalid file paths:* 

	* `translations/README.ar.md`


Feel free to re-request a review from me and I'll come back and take a look!

**Comment by OmarDev100** [comment]
Note: **Under Progress**

**Comment by OmarDev100** [comment]
Hey @github-education (@elisemoe)! Check out the new Arabic translation translated all by me!

_FYI (for your information):_ **Add it as "العربية" so people can understand (It is the name of the language in Arabic)**

My hope is that this translation **helps more people to join the event and make it expand!!!**

Thank you everyone and @github-education team!

**Comment by OmarDev100** [comment]
Status note: **Completed - Waiting for @github-education review**

**Comment by elisemoe** [comment]
Wow! Thank you so much @OmarDev100!! I'm sure this will help so many others participate in the event ✨

**Comment by OmarDev100** [comment]
YeY YeY YeY!!!

**Pull request merged**
