### PR TITLE
Fixing some issues at Indonesian Translation

### PR DESCRIPTION
**Pull request by Faris0520**
Hi, I made another pull request because there were some issues in Indonesian translation.

Thank you for you attention

### CODE REVIEW

**Review by github-education — CHANGES_REQUESTED** [review]
**Hi Faris0520,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/Faris0520/Faris0520.md` exists*
*Please ensure all changes are contained within the `_data/Faris0520/` directory. Invalid file paths:* 

	* `translations/README.id-id.md`


Feel free to re-request a review from me and I'll come back and take a look!

**Comment by elisemoe** [comment]
Thanks so much, @Faris0520! Do you mind resolving the merge conflicts and then I'll add your updates?

**Comment by Faris0520** [comment]
hmm ok

**Comment by elisemoe** [comment]
Thank-you!!

**Pull request merged**
