### PR TITLE
Added Author of Bangla translation

### PR DESCRIPTION
**Pull request by RupomChowdhury**

### CODE REVIEW

**Review by github-education — APPROVED** [review]
**Hi RupomChowdhury,**
**Welcome to graduation!**

I'm really sorry! It looks like you've already graduated in a previous year. This is for first time grads!

**Comment by RupomChowdhury** [comment]
@elisemoe help to merge this pull

**Comment by elisemoe** [comment]
Hi @RupomChowdhury! Please [link to your PR in this Issue](https://github.com/education/GitHubGraduation-2022/issues/4290) and we'll manually review your submission.

**Comment by RupomChowdhury** [comment]
Thanks @elisemoe ! I have liked my PR in [this isse](https://github.com/education/GitHubGraduation-2022/issues/4290) .

**Pull request closed without merging**
