### PR TITLE
Create yashpaneliya.md

### PR DESCRIPTION
**Pull request by yashpaneliya**
# Application to the Class of 2022🎓

This pull request template helps you complete an application to the **Class of 2022**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`yashpaneliya`) and markdown file.
- [x] I have submitted a [swag shipping form](https://airtable.com/shrVMo8ItH4wjsO9f).
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I have [added the event](https://calendar.google.com/calendar/u/0/r/eventedit?dates=20220611T200000Z/20220611T220000Z&details&location=https://www.twitch.tv/githubeducation&text=%F0%9F%8E%89%F0%9F%8E%8A+GitHub+Graduation+2022+%F0%9F%8E%89%F0%9F%8E%8A) to my Calendar.

### CODE REVIEW

**Review by github-education — APPROVED** [review]
**Hi yashpaneliya,**
**Welcome to graduation!**

I'm really sorry! It looks like you've already graduated in a previous year. This is for first time grads!

**Comment by yashpaneliya** [comment]
Hey @elisemoe,
By mistake a made a PR to the Graduation-2021 repo but as soon as I got to know about it, I closed that PR and made a new PR in the Graduation-2022 repo. I am graduating in 2022 and I am a first-time grad. Can you please fix this and approve my PR?

**Comment by elisemoe** [comment]
Thanks for letting us know @yashpaneliya! Please [link to your PR in this Issue](https://github.com/education/GitHubGraduation-2022/issues/4290) and we'll manually review your submissions.

**Comment by yashpaneliya** [comment]
Thank you for your reply. I submitted another PR and the issue is resolved now 😃

**Comment by Sanan4li** [comment]
@elisemoe same happened with me, I didn't have a student developer pack last year and I made a PR that was rejected last year but this time I had a valid student developer pack and created a PR. It was marked as "previously graduated". I have mentioned the PR link the in the issue too but worrying about the first 7500.

**Pull request closed without merging**
