### PR TITLE
Adding Hindi Translation

### PR DESCRIPTION
**Pull request by Saket-Upadhyay**
### Adding Hindi Translation for GitHub Graduation-2022 Readme.md

Added a new file `translations/README.hi.md` with Hindi translation of main Readme.md

### CODE REVIEW

**Review by github-education — CHANGES_REQUESTED** [review]
**Hi Saket-Upadhyay,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/Saket-Upadhyay/Saket-Upadhyay.md` exists*
*Please ensure all changes are contained within the `_data/Saket-Upadhyay/` directory. Invalid file paths:* 

	* `translations/README.hi.md`


Feel free to re-request a review from me and I'll come back and take a look!

**Review by harshit-paneri — COMMENTED** [review]
It's Good.

**Review by shivanisinghs25 — APPROVED** [review]

**Comment by mlarasusan** [comment]
Hey [Saket](https://github.com/Saket-Upadhyay), thank you so much for your contribution. This is awesome. It will help so many students during the event!

**Comment by Saket-Upadhyay** [comment]
@mlarasusan, merging this didn't add any files, and @akshatnigam in #3600 added the same file under his name. (Covered in detail [here](https://github.com/education/GitHubGraduation-2022/pull/3600#issuecomment-1119214733))

Please kindly look into this.

**Comment by mlarasusan** [comment]
Hey @Saket-Upadhyay, so sorry about that - looks like it's now solved :]

**Pull request merged**
