### PR TITLE
Create Naveenkumar0405.md

### PR DESCRIPTION
**Pull request by Naveenkumar0405**
# Application to the Class of 2022🎓

This pull request template helps you complete an application to the **Class of 2022**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`) and markdown file.
- [x] I have submitted a [swag shipping form](https://airtable.com/shrVMo8ItH4wjsO9f).
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I have [added the event](https://calendar.google.com/calendar/u/0/r/eventedit?dates=20220611T200000Z/20220611T220000Z&details&location=https://www.twitch.tv/githubeducation&text=%F0%9F%8E%89%F0%9F%8E%8A+GitHub+Graduation+2022+%F0%9F%8E%89%F0%9F%8E%8A) to my Calendar.

### CODE REVIEW

**Review by github-education — APPROVED** [review]
**Hi Naveenkumar0405,**
**Welcome to graduation!**

I'm really sorry! It looks like you've already graduated in a previous year. This is for first time grads!

**Comment by github-education** [comment]
Congratulations on graduating 🎓🎉. Your submission has been approved, and you're now part of the class of 2022! We will send you a letter and custom trading card 💌 to your home. Stay tuned for updates through our social media accounts and be sure to save the date for graduation!

**Comment by Naveenkumar0405** [comment]
I'm Naveen Kumar S pursing B.E Computer Science and Engineering final year
in Muthayammal Engineering College, Rasipuram. I applied for GitHub
Graduation 2022 program but I received the mail like " It looks like you've
already graduated in a previous year". I am graduate in this year 2022. So
please approve my application my PR #4935 and my GitHub username is
Naveenkumar0405. I am also attach my college Id card for proof and for your
reference. So please approve my application.

**Comment by lasr21** [comment]
Hi @Naveenkumar0405  we have already closed this year's graduation process.

**Pull request merged**
