### PR TITLE
Add Turkish translation

### PR DESCRIPTION
**Pull request by fybx**
I have completely translated the README to Turkish

### CODE REVIEW

**Review by github-education — CHANGES_REQUESTED** [review]
**Hi fybx,**
**Welcome to graduation!**


### I have a few items I need you to take care of before I can merge this PR:

* *I'm not seeing a valid student developer pack approval, please submit an [application](https://education.github.com/discount_requests/student_application?utm_source=2021-06-05-GitHubGraduation) to get started*
* *It looks like you still need to fill out the [shipping form](https://airtable.com/shrVMo8ItH4wjsO9f) to continue*
* *Uh Oh! I've found some issues with where you have created your files!* 
	*The required markdown file does not exist, please ensure the file `_data/fybx/fybx.md` exists*
*Please ensure all changes are contained within the `_data/fybx/` directory. Invalid file paths:* 

	* `translations/README.tr.md`

* *You need to agree to our COC on the shipping form pretty please!*

Feel free to re-request a review from me and I'll come back and take a look!

**Comment by juanpflores** [comment]
Hi there! 
Thanks for making the translation to Turkish! do you think that you can also add a link to the translation from the README and add a new row in the translation/README with a link to the translation and your username in the author section?

Thanks ⭐

**Comment by fybx** [comment]
I have added the links you've requested to `translations/README.md` and `README.md`

**Review by juanpflores — APPROVED** [review]
✅ LGTM

**Comment by juanpflores** [comment]
Thanks for helping out with this ⭐

**Pull request merged**
