### PR TITLE
Translated README in Simplified Chinese

### PR DESCRIPTION
**Pull request by iXeor**
Here is a Readme I translated in Simplified Chinese.Please review and if have any issue,please tell me.I'll update it as fast as I can.

### CODE REVIEW

**Comment by iXeor** [comment]
Hey.Maybe I pull this request in a wrong way.
I just try my best to translate README into Chinese instead pulling my graduation submission.
Here is my graduation submission request [Add iXeor.md file for Github Graduation 2022 #2991](https://github.com/education/GitHubGraduation-2022/pull/2991)
And this pull request is for translations.Please review again.Thanks so much.

**Comment by elisemoe** [comment]
You can tag me here or in a new Pull Request and I'll take a look!

**Comment by iXeor** [comment]
It’s my pleasure to improve it.I'll check it later.Then I would edit and ping you later.Thanks so much.

**Comment by iXeor** [comment]
@elisemoe Hi,Elise.I just update my commit now.Please review it.
And if you have some suggestions,please tell me.
I hope this translation could be better than before.
In our language,Chinese both means "中国人" and "中文".
When we describe the man is a Chinese,that means he or she is a "中国人".
And when we describe the language,the Chinese means "中文".

**Comment by iXeor** [comment]
> You can tag me here or in a new Pull Request and I'll take a look!

Done.Please check my translation.If have some feedback,please tell me.

**Pull request closed without merging**
