### PR TITLE
:tiger:

### PR DESCRIPTION
**Pull request by ArnavGohil**
# Application to the Class of 2022🎓

This pull request template helps you complete an application to the **Class of 2022**. Use the checklist below to verify you have followed the instructions correctly. 

## Checklist ✅

- [x] I have read the instructions on the README file before submitting my application. 
- [x] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`) and markdown file.
- [x] I have submitted a [swag shipping form](https://airtable.com/shrVMo8ItH4wjsO9f).
- [x] I have used the Markdown file template to add my information to the Year Book.
- [x] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [x] I understand I should not tag or add a reviewer to this Pull Request.
- [x] I have [added the event](http://www.google.com/calendar/event?action=TEMPLATE&dates=20210605T160000Z%2F20210605T173000Z&text=GitHub%20Graduation%20%F0%9F%8E%93&location=https%3A%2F%2Fwww.twitch.tv%2Fgithubeducation&details=) to my Calendar.

### CODE REVIEW

**Review by github-education — APPROVED** [review]
**Hi ArnavGohil,**
**Welcome to graduation!**

I'm really sorry! It looks like you've already graduated in a previous year. This is for first time grads!

**Comment by ArnavGohil** [comment]
Hi, I think there's been a mistake. I will be graduating in the coming month, ie May 2022

**Comment by asheeeshh** [comment]
It means that you had applied for Graduation 2021, people who already have joined in any of the previous graduation events can't join again.

**Comment by ArnavGohil** [comment]
I had created a PR by mistake last year in a hurry. Had closed it ASAP when I realised it was for 2021 grads
Screenshot 2022-05-03 at 4 01 38 PM

**Comment by asheeeshh** [comment]
are you sure it wasn't merged?

**Comment by ArnavGohil** [comment]
Yup 💯

**Comment by elisemoe** [comment]
Hi, @ArnavGohil 👋  thanks for letting us know! I've removed your submission from last year, and you should now be able to submit a Pull Request to participate.

Congrats on your graduation!

**Comment by ArnavGohil** [comment]
Hi @elisemoe ,  I created new pull request (https://github.com/education/GitHubGraduation-2022/pull/1924) but I am still my pull request is getting closed

**Comment by elisemoe** [comment]
Sorry for the confusion! Do you mind trying once more? We had a problem with the cache but have cleared it now.

**Comment by ArnavGohil** [comment]
Still no luck 😢 - https://github.com/education/GitHubGraduation-2022/pull/2691

**Comment by asheeeshh** [comment]
maybe deleting the PR from graduation 21 could help, not sure though

**Pull request closed without merging**
